// <auto-generated />
using System;
using Demo.MySQL.Pomelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.MySQL.Pomelo.Migrations
{
    [DbContext(typeof(Issue24Context))]
    partial class Issue24ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Demo.Base.Issue24.Book", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Create_Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<string>("Create_User")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("create_user")
                        .HasComment("创建者");

                    b.Property<bool>("Is_Soft_Deleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_soft_deleted")
                        .HasComment("是否软删除");

                    b.Property<int?>("Pages")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<DateTime?>("PubTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Row_Rersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("row_rersion")
                        .HasComment("行版本号");

                    b.Property<Guid?>("Title")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Update_Time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.Property<string>("Update_User")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("update_user")
                        .HasComment("更新者");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("T_Books");
                });
#pragma warning restore 612, 618
        }
    }
}
