using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;

namespace Zack.EFCore.Batch.Internal
{
    public static class BulkInsertUtils
    {
        public static bool IsNavigationProp(IEntityType entityType, PropertyInfo propInfo)
        {
            return entityType.FindNavigation(propInfo) != null;
        }

        /// <summary>
        /// Get properties except for navigationProperties or  autogenerated ones
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <param name="dbCtx"></param>
        /// <returns></returns>
        public static DbProp[] ParseDbProps<TEntity>(IEntityType entityType) where TEntity : class
        {
            //skip navigationProperties
            var props = typeof(TEntity).GetProperties().Where(p => !IsNavigationProp(entityType, p));
            List<DbProp> propFields = new List<DbProp>();

            foreach (var prop in props)
            {
                string propName = prop.Name;
                var efProp = entityType.GetProperty(propName);
                //skip the columns those are autogenerated
                if (efProp.ValueGenerated == ValueGenerated.OnAdd || efProp.ValueGenerated == ValueGenerated.OnAddOrUpdate)
                {
                    continue;
                }
                string dbColName = efProp.GetColumnName(StoreObjectIdentifier.SqlQuery(entityType));
                string dbColType = efProp.GetColumnType();
                DbProp dbProp = new DbProp
                {
                    ColumnName = dbColName,
                    ColumnType = dbColType,
                    Property = prop,
                    PropertyName = propName,
                    PropertyType = prop.PropertyType,
                    EFMeta = efProp
                };
                propFields.Add(dbProp);
            }
            return propFields.ToArray();
        }

        /// <summary>
        /// Build DataTable for items
        /// </summary>
        /// <typeparam name="TEntity"></typeparam>
        /// <param name="dbSet"></param>
        /// <param name="items"></param>
        /// <returns></returns>
        public static DataTable BuildDataTable<TEntity>(this DbSet<TEntity> dbSet,
            IEnumerable<TEntity> items) where TEntity : class
        {
            var entityType = dbSet.EntityType;
            var dbProps = ParseDbProps<TEntity>(entityType);            
            DataTable dataTable = new DataTable();
            foreach (var dbProp in dbProps)
            {
                string columnName = dbProp.ColumnName;
                dataTable.Columns.Add(columnName, dbProp.PropertyType);
            }
            foreach (var item in items)
            {
                DataRow row = dataTable.NewRow();
                foreach (var dbProp in dbProps)
                {
                    object value = dbProp.Property.GetValue(item);
                    row[dbProp.ColumnName] = value;
                }
                dataTable.Rows.Add(row);
            }
            return dataTable;
        }
    }
}
